### PR TITLE
refactor: Tags to classes

### PR DESCRIPTION
**Pull request by JasonEtco**
This PR converts all of the tags in `lib/liquid/tags/` to ES6 classes, with `async/await` methods instead of wonky Promises. It's going to be pretty difficult to review, because each tag is changed a good deal. I kept the same method names, signatures, etc - but the internals are all slightly different. Mostly I did the following:

* Removed unnecessary closures in favor of using `this` in a more class-y way
* Removed `var ...` in favor of `const` when we actually define the variable

This is all to achieve two things: have a more manageable codebase that we can make changes to, and to improve performance by removing unnecessary assignments (like the `extend` function, closures, etc).

The one change that I had to make outside of specific tags was to `engine.js`, to properly check for subclasses.

@zeke - how do you feel about this? Do you think we _should_ do this kind of refactoring (I don't mind taking it on)? Are we confident enough in the tests to know that this is a safe refactor?

If yes - how to we want to roll it out? I'd like to do it all at once as one big new version with the rest of the codebase getting udpates, but semantic-release will ship it per PR.

### CODE REVIEW

**Comment by zeke** [comment]
Wow! Thanks for jumping into this. ❤️ 

Even though this doesn't change the user-facing API, I'd suggest this refactor (and other big refactors that follow it) should probably land in a new major version for safety.

> I'd like to do it all at once as one big new version with the rest of the codebase getting udpates, but semantic-release will ship it per PR.

We could consider switching to https://github.com/googleapis/release-please for this project. From it's README:

> Rather than continuously releasing what's landed to your default branch, release-please maintains Release PRs [...] These Release PRs are kept up-to-date as additional work is merged. When you're ready to tag a release, simply merge the release PR.

We could also temporarily disable the semantic-release workflow, or just merge unsemantic PRs and wrap it all up with a semantic PR with `BREAKING CHANGE: ` in the extended body of the squashed commit when we're ready to cut a new release. 🤔 

Those are just ideas though. I'm open to however you wanna do this.

**Comment by JasonEtco** [comment]
> Even though this doesn't change the user-facing API, I'd suggest this refactor (and other big refactors that follow it) should probably land in a new major version for safety.

Yeah, 1000%. I'd like to bundle this and #112 into one big breaking change, ideally with some prerelease/beta versions while we verify that nothing has _actually_ changed. Still in favor of it being a major bump to be clear, I just wouldn't expect there to be any real-world changes.

**Comment by JasonEtco** [comment]
> just merge unsemantic PRs and wrap it all up with a semantic PR with BREAKING CHANGE: 

I'd opt for this, based on https://github.com/probot/probot/pull/1274 as prior art. We can also shift this to #112, since it encapsulates all the changes here, ++ the rest of the codebase.

**Comment by zeke** [comment]
Sounds good. Should we close this then?

**Comment by JasonEtco** [comment]
Yeah let's do it 👍

**Pull request closed without merging**
